version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ra45IUxi29a0G87b77oFOps72j1Jj1i7f7fnrnsoapz
      POSTGRES_DB: freelance

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "80:80"

    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: milsyaga@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ra45IUxi29a0G87b77oFOps72j1Jj1i7f7fnrnsoapz
    ports:
      - "5052:82"
    depends_on:
      - db