"""add total_spent and total_earned columns to profiles

Revision ID: b4f2c7d8e9a3
Revises: a18da8f6b289
Create Date: 2024-03-20 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f2c7d8e9a3'
down_revision: Union[str, None] = 'a18da8f6b289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('total_spent', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('profiles', sa.Column('total_earned', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'total_earned')
    op.drop_column('profiles', 'total_spent')
    # ### end Alembic commands ### 